server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/scut_app?serverTimezone=UTC
      username: root
      password: xuxin158263
  redis:
    host: 192.168.198.128
    password: xx158263
    port: 6379
    lettuce:
      pool:
        max-active: 8 # 最大连接
        max-idle: 8 # 最大空闲连接
        min-idle: 0 # 最小空闲连接
        max-wait: 100 # 连接等待时间

logging:
  level:
    root: info

# 开启 _ 与驼峰命名法映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
