spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/scut_app?serverTimezone=UTC
      username: root
      password: xuxin158263

      # 开启 _ 与驼峰命名法映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true